module ciaaw_version_f90
    !! Function for writing the Fortran code.
    use iso_fortran_env
    use core
    implicit none

    
contains

subroutine write_fortran_module_declaration(fcode, version)
    !! Generate the Fortran module declaration.
    implicit none
    ! Arguments
    integer(int32), intent(in) :: fcode
        !! File unit of the Fortran module.
    character(len=*), intent(in) :: version

    integer(int32) :: n 
    character(len=32) :: nstr

    n = len(trim(version)) - 2 ! remove quotes from computation
    
    write(nstr, "(I2)") n
    
    write(fcode, "(A)") "module ciaaw__version"
    write(fcode, "(A)") "!! Standard Atomic Weights - autogenerated."
    write(fcode, "(A)") "use iso_fortran_env"
    write(fcode, "(A)") "use ieee_arithmetic"
    write(fcode, "(A)") "implicit none"
    write(fcode, "(A, /)") "private"
    write(fcode, "(A)") 'character(len='//trim(nstr)//'), parameter, public :: ciaaw_version_version = '//version
    write(fcode, "(A)") ""
end subroutine


subroutine write_fortran_module_end(fcode)
    !! Generate the end of the Fortran module.
    implicit none
    ! Arguments
    integer(int32), intent(in) :: fcode
        !! File unit of the Fortran module.
    write(fcode, "(A)") "end module ciaaw__version"
end subroutine


end module