name = "ciaaw"
version = "0.1.0"
license = "GNU General Public License v3 (GPLv3)"
author = "Milan Skocic"
maintainer = "milan.skocic@icloud.com"
copyright = "Copyright 2023, Milan Skocic"
description = "Standard atomic weights according to CIAAW."
categories = ["Science", "Chemistry"]
keywords = ["atomic weights", "molar masses", "ciaaw"]
homepage = "https://milanskocic.github.io/ciaaw/index.html"

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = true

[install]
library = true

[[test]]
name = "test_saw"
main = "test_saw.f90"

[[test]]
name = "test_version"
main = "test_version.f90"

[[test]]
name = "test_saw_capi"
main = "test_saw_capi.c"

[[test]]
name = "test_version_capi"
main = "test_version_capi.c"

[[example]]
name = "example_in_f"
main = "example_in_f.f90"

[[example]]
name = "example_in_c"
main = "example_in_c.c"
