module fortran_code
    !! Function for writing the Fortran code.
    use iso_fortran_env
    implicit none
    
contains

subroutine write_fortran_module_declaration(fcode)
    !! brief Generate the Fortran module declaration.
    implicit none
    ! Arguments
    integer(int32), intent(in) :: fcode
        !! File unit of the Fortran module.
    
    write(fcode, "(A)") "module ciaaw__saw"
    write(fcode, "(A)") "!! Standard Atomic Weights - autogenerated."
    write(fcode, "(A)") "use iso_fortran_env"
    write(fcode, "(A)") "use ieee_arithmetic"
    write(fcode, "(A, /)") "implicit none"
    write(fcode, "(A)") "type :: ciaaw_saw_elmt_t"
    write(fcode, "(A)") 'character(len=32) :: element'
    write(fcode, "(A)") 'character(len=2) :: symbol'
    write(fcode, "(A)") 'integer(int32) :: z'
    write(fcode, "(A)") 'real(real64) :: saw_min'
    write(fcode, "(A)") 'real(real64) :: saw_max'
    write(fcode, "(A)") 'real(real64) :: saw'
    write(fcode, "(A)") 'real(real64) :: saw_u'
    write(fcode, "(A)") 'real(real64) :: asaw'
    write(fcode, "(A)") 'real(real64) :: asaw_u'
    write(fcode, "(A)") "end type"
    write(fcode, "(A)") ""
end subroutine


subroutine write_fortran_module_end(fcode)
    !! Generate the end of the Fortran module.
    implicit none
    ! Arguments
    integer(int32), intent(in) :: fcode
        !! File unit of the Fortran module.
    write(fcode, "(A)") "end module ciaaw__saw"
end subroutine

subroutine write_fortran_capi_module_declaration(fcode)
    !! Generate the Fortran CAPI module declaration.
    implicit none
    ! Arguments
    integer(int32), intent(in) :: fcode
        !! File unit of the Fortran module.
    
    write(fcode, "(A)") "module ciaaw__saw_capi"
    write(fcode, "(A)") "!! Standard Atomic Weights - autogenerated."
    write(fcode, "(A)") "use iso_c_binding"
    write(fcode, "(A)") "use ciaaw__saw"
    write(fcode, "(A, /)") "implicit none"
    write(fcode, "(A)") "type, bind(C) :: ciaaw_saw_capi_elmt_t"
    write(fcode, "(A)") 'character(kind=c_char) :: element(33)'
    write(fcode, "(A)") 'character(kind=c_char) :: symbol(3)'
    write(fcode, "(A)") "integer(c_int) :: z"
    write(fcode, "(A)") 'real(c_double) :: saw_min'
    write(fcode, "(A)") 'real(c_double) :: saw_max'
    write(fcode, "(A)") 'real(c_double) :: saw'
    write(fcode, "(A)") 'real(c_double) :: saw_u'
    write(fcode, "(A)") 'real(c_double) :: asaw'
    write(fcode, "(A)") 'real(c_double) :: asaw_u'
    write(fcode, "(A)") "end type"
    write(fcode, "(A)") ""
end subroutine


subroutine write_fortran_capi_module_end(fcode)
    !! Generate the end of the Fortran CAPI module.
    implicit none
    ! Arguments
    integer(int32), intent(in) :: fcode
        !! File unit of the Fortran module.
    write(fcode, "(A)") "end module ciaaw__saw_capi"
end subroutine


subroutine write_C_header_declaration(fcode)
    !! Generate the C header declaration
    implicit none
    ! Arguments
    integer(int32), intent(in) :: fcode
        !! File unit of the C header.
    write(fcode, "(A)") '#ifndef CIAAW_SAW_H'
    write(fcode, "(A)") '#define CIAAW_SAW_H'

    write(fcode, "(A)") 'struct ciaaw_saw_capi_elmt_t{'
    write(fcode, "(4X, A)") 'char element[33];'
    write(fcode, "(4X, A)") 'char symbol[3];'
    write(fcode, "(4X, A)") 'int z;'
    write(fcode, "(4X, A)") 'double saw_min;'
    write(fcode, "(4X, A)") 'double saw_max;'
    write(fcode, "(4X, A)") 'double saw;'
    write(fcode, "(4X, A)") 'double saw_u;'
    write(fcode, "(4X, A)") 'double asaw;'
    write(fcode, "(4X, A)") 'double asaw_u;'
     write(fcode, "(A)") '};'
    
end subroutine


subroutine write_C_header_end(fcode)
    !! Generate the C header declaration
    implicit none
    ! Arguments
    integer(int32), intent(in) :: fcode
        !! File unit of the C header.
    write(fcode, "(A)") '#endif'
    write(fcode, "(A)") ''
    
end subroutine

end module