program generator
    use iso_fortran_env
    implicit none
    
    integer(int32) :: fciaaw
    integer(int32) :: ffortran
    integer(int32) :: unit
    logical :: exist

    ! CODATA SOURCE
    print *, "Opening ciaaw file..."
    open(file="./ciaaw_2021.txt", newunit=fciaaw, status="old", action="read")
    
    ! FORTRAN
    print *, "Opening ffortran file..."
    inquire(file="../src/ciaaw_saw.f90", exist=exist)
    if(exist)then
        open(file="../src/ciaaw_saw.f90", newunit=unit, status="old")
        close(unit=unit, status="delete")
    endif
    open(file="../src/ciaaw_saw.f90", newunit=ffortran, status="new", action="write")

    call write_fortran_module_declaration(ffortran)

    call write_fortran_module_end(ffortran)


    close(ffortran)

contains

subroutine write_fortran_module_declaration(fcode)
    !! brief Generate the Fortran module declaration.
    implicit none
    ! Arguments
    integer(int32), intent(in) :: fcode
        !! File unit of the Fortran module.
    
    write(fcode, "(A)") "module ciaaw__saw"
    write(fcode, "(A)") "!! Standard Atomic Weights - autogenerated."
    write(fcode, "(A)") "use iso_fortran_env"
    write(fcode, "(A)") "implicit none"
    write(fcode, "(A)") " "
end subroutine


subroutine write_fortran_module_end(fcode)
    !! Generate the end of the Fortran module.
    implicit none
    ! Arguments
    integer(int32), intent(in) :: fcode
        !! File unit of the Fortran module.
    write(fcode, "(A)") "end module ciaaw__saw"
end subroutine

subroutine write_saw_data(fcode)
    !! Generate the fortran code for ciaaw__saw.
    implicit none
    ! Arguments
    integer(int32), intent(in) :: fcode
        !! File unit of the Fortran module.

    

end subroutine

end program