/**
* @file
* @brief C API Standard Atomic Weights - autogenerated.
*/

#ifndef CIAAW_SAW_H
#define CIAAW_SAW_H
#if _MSC_VER
#define ADD_IMPORT __declspec(dllimport)
#else
#define ADD_IMPORT
#endif
/** @brief C API Object representing an element.*/
struct ciaaw_saw_element_t{
    char element[25]; /**< Element name. */
    char symbol[9]; /**< Element symbol. */
    int z; /**< Element atomic number. */
    double saw_min; /**< Min standard atomic weight. */
    double saw_max; /**< Max standard atomic weight. */
    double saw; /**< Value standard atomic weight. */
    double saw_u; /**< Uncertainty standard atomic weight. */
    double asaw; /**< Abridged value standard atomic weight. */
    double asaw_u; /**< Abridged uncertainty standard atomic weight. */
};
ADD_IMPORT extern const int ciaaw_saw_YEAR; /**< C API Publication year. */

ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_H;/**< C API H.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_He;/**< C API He.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Li;/**< C API Li.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Be;/**< C API Be.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_B;/**< C API B.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_C;/**< C API C.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_N;/**< C API N.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_O;/**< C API O.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_F;/**< C API F.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ne;/**< C API Ne.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Na;/**< C API Na.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Mg;/**< C API Mg.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Al;/**< C API Al.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Si;/**< C API Si.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_P;/**< C API P.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_S;/**< C API S.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Cl;/**< C API Cl.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ar;/**< C API Ar.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_K;/**< C API K.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ca;/**< C API Ca.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Sc;/**< C API Sc.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ti;/**< C API Ti.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_V;/**< C API V.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Cr;/**< C API Cr.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Mn;/**< C API Mn.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Fe;/**< C API Fe.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Co;/**< C API Co.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ni;/**< C API Ni.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Cu;/**< C API Cu.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Zn;/**< C API Zn.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ga;/**< C API Ga.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ge;/**< C API Ge.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_As;/**< C API As.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Se;/**< C API Se.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Br;/**< C API Br.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Kr;/**< C API Kr.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Rb;/**< C API Rb.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Sr;/**< C API Sr.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Y;/**< C API Y.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Zr;/**< C API Zr.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Nb;/**< C API Nb.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Mo;/**< C API Mo.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Tc;/**< C API Tc.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ru;/**< C API Ru.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Rh;/**< C API Rh.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Pd;/**< C API Pd.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ag;/**< C API Ag.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Cd;/**< C API Cd.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_In;/**< C API In.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Sn;/**< C API Sn.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Sb;/**< C API Sb.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Te;/**< C API Te.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_I;/**< C API I.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Xe;/**< C API Xe.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Cs;/**< C API Cs.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ba;/**< C API Ba.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_La;/**< C API La.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ce;/**< C API Ce.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Pr;/**< C API Pr.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Nd;/**< C API Nd.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Pm;/**< C API Pm.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Sm;/**< C API Sm.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Eu;/**< C API Eu.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Gd;/**< C API Gd.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Tb;/**< C API Tb.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Dy;/**< C API Dy.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ho;/**< C API Ho.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Er;/**< C API Er.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Tm;/**< C API Tm.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Yb;/**< C API Yb.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Lu;/**< C API Lu.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Hf;/**< C API Hf.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ta;/**< C API Ta.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_W;/**< C API W.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Re;/**< C API Re.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Os;/**< C API Os.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ir;/**< C API Ir.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Pt;/**< C API Pt.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Au;/**< C API Au.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Hg;/**< C API Hg.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Tl;/**< C API Tl.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Pb;/**< C API Pb.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Bi;/**< C API Bi.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Po;/**< C API Po.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_At;/**< C API At.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Rn;/**< C API Rn.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Fr;/**< C API Fr.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ra;/**< C API Ra.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ac;/**< C API Ac.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Th;/**< C API Th.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Pa;/**< C API Pa.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_U;/**< C API U.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Np;/**< C API Np.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Pu;/**< C API Pu.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Am;/**< C API Am.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Cm;/**< C API Cm.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Bk;/**< C API Bk.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Cf;/**< C API Cf.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Es;/**< C API Es.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Fm;/**< C API Fm.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Md;/**< C API Md.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_No;/**< C API No.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Lr;/**< C API Lr.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Rf;/**< C API Rf.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Db;/**< C API Db.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Sg;/**< C API Sg.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Bh;/**< C API Bh.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Hs;/**< C API Hs.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Mt;/**< C API Mt.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ds;/**< C API Ds.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Rg;/**< C API Rg.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Cn;/**< C API Cn.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Nh;/**< C API Nh.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Fl;/**< C API Fl.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Mc;/**< C API Mc.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Lv;/**< C API Lv.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ts;/**< C API Ts.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Og;/**< C API Og.*/

#endif

