module ciaaw_saw_f90
    !! Function for writing the Fortran code.
    use iso_fortran_env
    use core
    implicit none

    
contains

subroutine write_fortran_module_declaration(fcode)
    !! Generate the Fortran module declaration.
    implicit none
    ! Arguments
    integer(int32), intent(in) :: fcode
        !! File unit of the Fortran module.

    character(len=32) :: S_LENGTH_ELEMENT
    character(len=32) :: S_LENGTH_SYMBOL

    write(S_LENGTH_ELEMENT, "(I2)") LENGTH_ELEMENT
    write(S_LENGTH_SYMBOL, "(I1)") LENGTH_SYMBOL
    
    write(fcode, "(A)") "module ciaaw__saw"
    write(fcode, "(A)") "!! Standard Atomic Weights - autogenerated."
    write(fcode, "(A)") "use iso_fortran_env"
    write(fcode, "(A)") "use iso_c_binding"
    write(fcode, "(A)") "use ieee_arithmetic"
    write(fcode, "(A)") "implicit none"
    write(fcode, "(A, /)") "private"
    write(fcode, "(A)") "integer(int64), parameter :: x = 1"
    write(fcode, "(A, /)") "real(real64), parameter :: nan = transfer(huge(x), 1.0d0)"
    write(fcode, "(A)") "type, public :: element_t"
    write(fcode, "(A)") "!! Object representing an element."
    write(fcode, "(A)") 'character(len='//trim(S_LENGTH_ELEMENT)//') :: element !! Element name'
    write(fcode, "(A)") 'character(len='//trim(S_LENGTH_SYMBOL)//') :: symbol !! Element symbol'
    write(fcode, "(A)") 'integer(int32) :: z !! Element atomic number'
    write(fcode, "(A)") 'real(real64) :: saw_min !! Min standard atomic weight'
    write(fcode, "(A)") 'real(real64) :: saw_max !! Max standard atomic weight'
    write(fcode, "(A)") 'real(real64) :: saw !! Value standard atomic weight'
    write(fcode, "(A)") 'real(real64) :: saw_u !! Uncertainty standard atomic weight'
    write(fcode, "(A)") 'real(real64) :: asaw !! Abridged value standard atomic weight'
    write(fcode, "(A)") 'real(real64) :: asaw_u !! Abridged uncertainty standard atomic weight'
    write(fcode, "(A)") "end type"
    write(fcode, "(A)") ""
    
    write(S_LENGTH_ELEMENT, "(I2)") LENGTH_ELEMENT+1
    write(S_LENGTH_SYMBOL, "(I1)") LENGTH_SYMBOL+1
    
    write(fcode, "(A)") "type, public, bind(C) :: capi_element_t"
    write(fcode, "(A)") "!! Object representing an element."
    write(fcode, "(A)") 'character(kind=c_char) :: element('//trim(S_LENGTH_ELEMENT)//') !! Element name'
    write(fcode, "(A)") 'character(kind=c_char) :: symbol('//trim(S_LENGTH_SYMBOL)//') !! Element symbol'
    write(fcode, "(A)") 'integer(c_int) :: z !! Element atomic number'
    write(fcode, "(A)") 'real(c_double) :: saw_min !! Min standard atomic weight'
    write(fcode, "(A)") 'real(c_double) :: saw_max !! Max standard atomic weight'
    write(fcode, "(A)") 'real(c_double) :: saw !! Value standard atomic weight'
    write(fcode, "(A)") 'real(c_double) :: saw_u !! Uncertainty standard atomic weight'
    write(fcode, "(A)") 'real(c_double) :: asaw !! Abridged value standard atomic weight'
    write(fcode, "(A)") 'real(c_double) :: asaw_u !! Abridged uncertainty standard atomic weight'
    write(fcode, "(A)") "end type"
    write(fcode, "(A)") ""
end subroutine


subroutine write_fortran_module_end(fcode)
    !! Generate the end of the Fortran module.
    implicit none
    ! Arguments
    integer(int32), intent(in) :: fcode
        !! File unit of the Fortran module.
    write(fcode, "(A)") "end module ciaaw__saw"
end subroutine

end module