/**
* @file
* @brief C API - Standard Atomic Weights 2021 - autogenerated.
*/

#ifndef CIAAW_SAW_H_2021
#define CIAAW_SAW_H_2021
#if _MSC_VER
#define ADD_IMPORT __declspec(dllimport)
#else
#define ADD_IMPORT
#endif
#include "ciaaw_saw_type.h"
ADD_IMPORT extern const int YEAR_2021; /**< C API Publication year. */

ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_H_2021;/**< C API H_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_He_2021;/**< C API He_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Li_2021;/**< C API Li_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Be_2021;/**< C API Be_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_B_2021;/**< C API B_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_C_2021;/**< C API C_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_N_2021;/**< C API N_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_O_2021;/**< C API O_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_F_2021;/**< C API F_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ne_2021;/**< C API Ne_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Na_2021;/**< C API Na_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Mg_2021;/**< C API Mg_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Al_2021;/**< C API Al_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Si_2021;/**< C API Si_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_P_2021;/**< C API P_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_S_2021;/**< C API S_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Cl_2021;/**< C API Cl_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ar_2021;/**< C API Ar_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_K_2021;/**< C API K_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ca_2021;/**< C API Ca_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Sc_2021;/**< C API Sc_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ti_2021;/**< C API Ti_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_V_2021;/**< C API V_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Cr_2021;/**< C API Cr_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Mn_2021;/**< C API Mn_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Fe_2021;/**< C API Fe_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Co_2021;/**< C API Co_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ni_2021;/**< C API Ni_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Cu_2021;/**< C API Cu_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Zn_2021;/**< C API Zn_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ga_2021;/**< C API Ga_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ge_2021;/**< C API Ge_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_As_2021;/**< C API As_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Se_2021;/**< C API Se_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Br_2021;/**< C API Br_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Kr_2021;/**< C API Kr_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Rb_2021;/**< C API Rb_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Sr_2021;/**< C API Sr_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Y_2021;/**< C API Y_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Zr_2021;/**< C API Zr_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Nb_2021;/**< C API Nb_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Mo_2021;/**< C API Mo_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Tc_2021;/**< C API Tc_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ru_2021;/**< C API Ru_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Rh_2021;/**< C API Rh_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Pd_2021;/**< C API Pd_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ag_2021;/**< C API Ag_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Cd_2021;/**< C API Cd_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_In_2021;/**< C API In_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Sn_2021;/**< C API Sn_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Sb_2021;/**< C API Sb_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Te_2021;/**< C API Te_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_I_2021;/**< C API I_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Xe_2021;/**< C API Xe_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Cs_2021;/**< C API Cs_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ba_2021;/**< C API Ba_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_La_2021;/**< C API La_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ce_2021;/**< C API Ce_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Pr_2021;/**< C API Pr_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Nd_2021;/**< C API Nd_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Pm_2021;/**< C API Pm_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Sm_2021;/**< C API Sm_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Eu_2021;/**< C API Eu_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Gd_2021;/**< C API Gd_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Tb_2021;/**< C API Tb_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Dy_2021;/**< C API Dy_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ho_2021;/**< C API Ho_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Er_2021;/**< C API Er_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Tm_2021;/**< C API Tm_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Yb_2021;/**< C API Yb_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Lu_2021;/**< C API Lu_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Hf_2021;/**< C API Hf_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ta_2021;/**< C API Ta_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_W_2021;/**< C API W_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Re_2021;/**< C API Re_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Os_2021;/**< C API Os_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ir_2021;/**< C API Ir_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Pt_2021;/**< C API Pt_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Au_2021;/**< C API Au_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Hg_2021;/**< C API Hg_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Tl_2021;/**< C API Tl_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Pb_2021;/**< C API Pb_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Bi_2021;/**< C API Bi_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Po_2021;/**< C API Po_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_At_2021;/**< C API At_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Rn_2021;/**< C API Rn_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Fr_2021;/**< C API Fr_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ra_2021;/**< C API Ra_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ac_2021;/**< C API Ac_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Th_2021;/**< C API Th_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Pa_2021;/**< C API Pa_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_U_2021;/**< C API U_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Np_2021;/**< C API Np_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Pu_2021;/**< C API Pu_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Am_2021;/**< C API Am_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Cm_2021;/**< C API Cm_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Bk_2021;/**< C API Bk_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Cf_2021;/**< C API Cf_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Es_2021;/**< C API Es_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Fm_2021;/**< C API Fm_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Md_2021;/**< C API Md_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_No_2021;/**< C API No_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Lr_2021;/**< C API Lr_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Rf_2021;/**< C API Rf_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Db_2021;/**< C API Db_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Sg_2021;/**< C API Sg_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Bh_2021;/**< C API Bh_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Hs_2021;/**< C API Hs_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Mt_2021;/**< C API Mt_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ds_2021;/**< C API Ds_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Rg_2021;/**< C API Rg_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Cn_2021;/**< C API Cn_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Nh_2021;/**< C API Nh_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Fl_2021;/**< C API Fl_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Mc_2021;/**< C API Mc_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Lv_2021;/**< C API Lv_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Ts_2021;/**< C API Ts_2021.*/
ADD_IMPORT extern const struct ciaaw_saw_element_t ciaaw_saw_Og_2021;/**< C API Og_2021.*/

#endif

