/**
* @file
* @brief Version - autogenerated.
*/

#ifndef CIAAW_VERSION_H
#define CIAAW_VERSION_H
#if _MSC_VER
#define ADD_IMPORT __declspec(dllimport)
#else
#define ADD_IMPORT
#endif
extern const char ciaaw_version_capi_version[ 6];
#endif

