.TH ciaaw_nnaw 3 "18 July 2026" "1.3.2" "Library Functions Manual"

.SH NAME
\"{{{
nnaw \- function
\"}}}

.SH LIBRARY
\"{{{
ciaaw library 
.RI ( libciaaw ", " \-lciaaw )
\"}}}

.SH SYNOPSIS
\"{{{
.IP Fortran 10
.BI "function nnaw(" s ")result(" res ")"
.RS
.IP "" 3
.BI "character(len=*), intent(in)  :: " s   
.IP "" 3
.BI "integer(int32)  :: " res               
.RE

.IP C 10
.BI "int ciaaw_nnaw(char *" s, "int " n ");"

.IP Python 10
.BI nnaw( s: str)->int
\"}}}

.SH DESCRIPTION
Get the number of nuclides in NAW of the element \fIs\fP.

Arguments:
.IP \fIs\fP 10
Element symbol.
.IP \fIn\fP 10
Size of the string \fIs\fP.

.SH RETURN VALUE
.IP -1 10 
If the provided element is incorrect.
.IP >0 10  
If the element has NAW.
.SH SEE ALSO
.BR ciaaw (3),
.BR ciaaw_cli (1),
.BR ciaaw_version (3),
.BR ciaaw_saw (3),
.BR ciaaw_ice (3),
.BR ciaaw_nice (3),
.BR ciaaw_naw (3), 
.BR ciaaw_nnaw (3)
