.TH ciaaw_naws 3 "@DATE@" "@VERSION@" "Library calls"

.SH NAME
\"{{{
ices \- get all the nuclides' atomic weights
\"}}}

.SH LIBRARY
\"{{{
ciaaw library 
.RI ( libciaaw ", " \-lciaaw )
\"}}}

.SH SYNOPSIS
\"{{{
.IP Fortran 10
.BI "function naws(" s )result(res)
.RS
.IP "" 3
.BI "character(len=*), intent(in)  :: " s             
.IP "" 3
.BI "real(dp), pointer  :: " res(:,:)                 
.RE

.IP C 10
.BI "double *ciaaw_naws(char *" s, "int " n );

\"}}}

.SH DESCRIPTION
Get all nuclides' atomic weights of the element \fIs\fP.

Arguments:
.IP \fIs\fP 10
Element symbol.

.SH RETURN VALUE
.IP (n,3)array 10
Fortran order array with the mass number, the atomic weight and the 
uncertainty for the \fIn\fP nuclides given by \fBciaaw_nnaw(3)\fP.
.IP NULL 10 
If the provided element is incorrect.
