module ciaaw__capi_saw_2021
    !! Codata Constants - Autogenerated: C API.
    use iso_c_binding, only: c_null_char, c_int
    use ciaaw__saw_2021
    use ciaaw__capi_saw_type
    private

integer(c_int), protected, public, bind(C, name="ciaaw_saw_YEAR") :: capi_YEAR = YEAR !capi

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_H") ::&
capi_0 = capi_saw_type(&
["h","y","d","r","o","g","e","n",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["H",c_null_char," "," "," "," "," "," "," "], &
H%z, &
H%saw_min, &
H%saw_max, &
H%saw, &
H%saw_u, &
H%asaw, &
H%saw_u, &
["m",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_He") ::&
capi_1 = capi_saw_type(&
["h","e","l","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["H","e",c_null_char," "," "," "," "," "," "], &
He%z, &
He%saw_min, &
He%saw_max, &
He%saw, &
He%saw_u, &
He%asaw, &
He%saw_u, &
["g"," ","r",c_null_char," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Li") ::&
capi_2 = capi_saw_type(&
["l","i","t","h","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["L","i",c_null_char," "," "," "," "," "," "], &
Li%z, &
Li%saw_min, &
Li%saw_max, &
Li%saw, &
Li%saw_u, &
Li%asaw, &
Li%saw_u, &
["m",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Be") ::&
capi_3 = capi_saw_type(&
["b","e","r","y","l","l","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["B","e",c_null_char," "," "," "," "," "," "], &
Be%z, &
Be%saw_min, &
Be%saw_max, &
Be%saw, &
Be%saw_u, &
Be%asaw, &
Be%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_B") ::&
capi_4 = capi_saw_type(&
["b","o","r","o","n",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["B",c_null_char," "," "," "," "," "," "," "], &
B%z, &
B%saw_min, &
B%saw_max, &
B%saw, &
B%saw_u, &
B%asaw, &
B%saw_u, &
["m",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_C") ::&
capi_5 = capi_saw_type(&
["c","a","r","b","o","n",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["C",c_null_char," "," "," "," "," "," "," "], &
C%z, &
C%saw_min, &
C%saw_max, &
C%saw, &
C%saw_u, &
C%asaw, &
C%saw_u, &
["m",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_N") ::&
capi_6 = capi_saw_type(&
["n","i","t","r","o","g","e","n",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["N",c_null_char," "," "," "," "," "," "," "], &
N%z, &
N%saw_min, &
N%saw_max, &
N%saw, &
N%saw_u, &
N%asaw, &
N%saw_u, &
["m",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_O") ::&
capi_7 = capi_saw_type(&
["o","x","y","g","e","n",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["O",c_null_char," "," "," "," "," "," "," "], &
O%z, &
O%saw_min, &
O%saw_max, &
O%saw, &
O%saw_u, &
O%asaw, &
O%saw_u, &
["m",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_F") ::&
capi_8 = capi_saw_type(&
["f","l","u","o","r","i","n","e",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["F",c_null_char," "," "," "," "," "," "," "], &
F%z, &
F%saw_min, &
F%saw_max, &
F%saw, &
F%saw_u, &
F%asaw, &
F%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Ne") ::&
capi_9 = capi_saw_type(&
["n","e","o","n",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["N","e",c_null_char," "," "," "," "," "," "], &
Ne%z, &
Ne%saw_min, &
Ne%saw_max, &
Ne%saw, &
Ne%saw_u, &
Ne%asaw, &
Ne%saw_u, &
["g"," ","m",c_null_char," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Na") ::&
capi_10 = capi_saw_type(&
["s","o","d","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["N","a",c_null_char," "," "," "," "," "," "], &
Na%z, &
Na%saw_min, &
Na%saw_max, &
Na%saw, &
Na%saw_u, &
Na%asaw, &
Na%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Mg") ::&
capi_11 = capi_saw_type(&
["m","a","g","n","e","s","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["M","g",c_null_char," "," "," "," "," "," "], &
Mg%z, &
Mg%saw_min, &
Mg%saw_max, &
Mg%saw, &
Mg%saw_u, &
Mg%asaw, &
Mg%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Al") ::&
capi_12 = capi_saw_type(&
["a","l","u","m","i","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["A","l",c_null_char," "," "," "," "," "," "], &
Al%z, &
Al%saw_min, &
Al%saw_max, &
Al%saw, &
Al%saw_u, &
Al%asaw, &
Al%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Si") ::&
capi_13 = capi_saw_type(&
["s","i","l","i","c","o","n",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["S","i",c_null_char," "," "," "," "," "," "], &
Si%z, &
Si%saw_min, &
Si%saw_max, &
Si%saw, &
Si%saw_u, &
Si%asaw, &
Si%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_P") ::&
capi_14 = capi_saw_type(&
["p","h","o","s","p","h","o","r","u","s",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["P",c_null_char," "," "," "," "," "," "," "], &
P%z, &
P%saw_min, &
P%saw_max, &
P%saw, &
P%saw_u, &
P%asaw, &
P%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_S") ::&
capi_15 = capi_saw_type(&
["s","u","l","f","u","r",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["S",c_null_char," "," "," "," "," "," "," "], &
S%z, &
S%saw_min, &
S%saw_max, &
S%saw, &
S%saw_u, &
S%asaw, &
S%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Cl") ::&
capi_16 = capi_saw_type(&
["c","h","l","o","r","i","n","e",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["C","l",c_null_char," "," "," "," "," "," "], &
Cl%z, &
Cl%saw_min, &
Cl%saw_max, &
Cl%saw, &
Cl%saw_u, &
Cl%asaw, &
Cl%saw_u, &
["m",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Ar") ::&
capi_17 = capi_saw_type(&
["a","r","g","o","n",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["A","r",c_null_char," "," "," "," "," "," "], &
Ar%z, &
Ar%saw_min, &
Ar%saw_max, &
Ar%saw, &
Ar%saw_u, &
Ar%asaw, &
Ar%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_K") ::&
capi_18 = capi_saw_type(&
["p","o","t","a","s","s","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["K",c_null_char," "," "," "," "," "," "," "], &
K%z, &
K%saw_min, &
K%saw_max, &
K%saw, &
K%saw_u, &
K%asaw, &
K%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Ca") ::&
capi_19 = capi_saw_type(&
["c","a","l","c","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["C","a",c_null_char," "," "," "," "," "," "], &
Ca%z, &
Ca%saw_min, &
Ca%saw_max, &
Ca%saw, &
Ca%saw_u, &
Ca%asaw, &
Ca%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Sc") ::&
capi_20 = capi_saw_type(&
["s","c","a","n","d","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["S","c",c_null_char," "," "," "," "," "," "], &
Sc%z, &
Sc%saw_min, &
Sc%saw_max, &
Sc%saw, &
Sc%saw_u, &
Sc%asaw, &
Sc%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Ti") ::&
capi_21 = capi_saw_type(&
["t","i","t","a","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["T","i",c_null_char," "," "," "," "," "," "], &
Ti%z, &
Ti%saw_min, &
Ti%saw_max, &
Ti%saw, &
Ti%saw_u, &
Ti%asaw, &
Ti%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_V") ::&
capi_22 = capi_saw_type(&
["v","a","n","a","d","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["V",c_null_char," "," "," "," "," "," "," "], &
V%z, &
V%saw_min, &
V%saw_max, &
V%saw, &
V%saw_u, &
V%asaw, &
V%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Cr") ::&
capi_23 = capi_saw_type(&
["c","h","r","o","m","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["C","r",c_null_char," "," "," "," "," "," "], &
Cr%z, &
Cr%saw_min, &
Cr%saw_max, &
Cr%saw, &
Cr%saw_u, &
Cr%asaw, &
Cr%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Mn") ::&
capi_24 = capi_saw_type(&
["m","a","n","g","a","n","e","s","e",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["M","n",c_null_char," "," "," "," "," "," "], &
Mn%z, &
Mn%saw_min, &
Mn%saw_max, &
Mn%saw, &
Mn%saw_u, &
Mn%asaw, &
Mn%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Fe") ::&
capi_25 = capi_saw_type(&
["i","r","o","n",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["F","e",c_null_char," "," "," "," "," "," "], &
Fe%z, &
Fe%saw_min, &
Fe%saw_max, &
Fe%saw, &
Fe%saw_u, &
Fe%asaw, &
Fe%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Co") ::&
capi_26 = capi_saw_type(&
["c","o","b","a","l","t",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["C","o",c_null_char," "," "," "," "," "," "], &
Co%z, &
Co%saw_min, &
Co%saw_max, &
Co%saw, &
Co%saw_u, &
Co%asaw, &
Co%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Ni") ::&
capi_27 = capi_saw_type(&
["n","i","c","k","e","l",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["N","i",c_null_char," "," "," "," "," "," "], &
Ni%z, &
Ni%saw_min, &
Ni%saw_max, &
Ni%saw, &
Ni%saw_u, &
Ni%asaw, &
Ni%saw_u, &
["r",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Cu") ::&
capi_28 = capi_saw_type(&
["c","o","p","p","e","r",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["C","u",c_null_char," "," "," "," "," "," "], &
Cu%z, &
Cu%saw_min, &
Cu%saw_max, &
Cu%saw, &
Cu%saw_u, &
Cu%asaw, &
Cu%saw_u, &
["r",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Zn") ::&
capi_29 = capi_saw_type(&
["z","i","n","c",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["Z","n",c_null_char," "," "," "," "," "," "], &
Zn%z, &
Zn%saw_min, &
Zn%saw_max, &
Zn%saw, &
Zn%saw_u, &
Zn%asaw, &
Zn%saw_u, &
["r",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Ga") ::&
capi_30 = capi_saw_type(&
["g","a","l","l","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["G","a",c_null_char," "," "," "," "," "," "], &
Ga%z, &
Ga%saw_min, &
Ga%saw_max, &
Ga%saw, &
Ga%saw_u, &
Ga%asaw, &
Ga%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Ge") ::&
capi_31 = capi_saw_type(&
["g","e","r","m","a","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["G","e",c_null_char," "," "," "," "," "," "], &
Ge%z, &
Ge%saw_min, &
Ge%saw_max, &
Ge%saw, &
Ge%saw_u, &
Ge%asaw, &
Ge%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_As") ::&
capi_32 = capi_saw_type(&
["a","r","s","e","n","i","c",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["A","s",c_null_char," "," "," "," "," "," "], &
As%z, &
As%saw_min, &
As%saw_max, &
As%saw, &
As%saw_u, &
As%asaw, &
As%saw_u, &
["r",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Se") ::&
capi_33 = capi_saw_type(&
["s","e","l","e","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["S","e",c_null_char," "," "," "," "," "," "], &
Se%z, &
Se%saw_min, &
Se%saw_max, &
Se%saw, &
Se%saw_u, &
Se%asaw, &
Se%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Br") ::&
capi_34 = capi_saw_type(&
["b","r","o","m","i","n","e",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["B","r",c_null_char," "," "," "," "," "," "], &
Br%z, &
Br%saw_min, &
Br%saw_max, &
Br%saw, &
Br%saw_u, &
Br%asaw, &
Br%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Kr") ::&
capi_35 = capi_saw_type(&
["k","r","y","p","t","o","n",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["K","r",c_null_char," "," "," "," "," "," "], &
Kr%z, &
Kr%saw_min, &
Kr%saw_max, &
Kr%saw, &
Kr%saw_u, &
Kr%asaw, &
Kr%saw_u, &
["g"," ","m",c_null_char," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Rb") ::&
capi_36 = capi_saw_type(&
["r","u","b","i","d","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["R","b",c_null_char," "," "," "," "," "," "], &
Rb%z, &
Rb%saw_min, &
Rb%saw_max, &
Rb%saw, &
Rb%saw_u, &
Rb%asaw, &
Rb%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Sr") ::&
capi_37 = capi_saw_type(&
["s","t","r","o","n","t","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["S","r",c_null_char," "," "," "," "," "," "], &
Sr%z, &
Sr%saw_min, &
Sr%saw_max, &
Sr%saw, &
Sr%saw_u, &
Sr%asaw, &
Sr%saw_u, &
["g"," ","r",c_null_char," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Y") ::&
capi_38 = capi_saw_type(&
["y","t","t","r","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["Y",c_null_char," "," "," "," "," "," "," "], &
Y%z, &
Y%saw_min, &
Y%saw_max, &
Y%saw, &
Y%saw_u, &
Y%asaw, &
Y%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Zr") ::&
capi_39 = capi_saw_type(&
["z","i","r","c","o","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["Z","r",c_null_char," "," "," "," "," "," "], &
Zr%z, &
Zr%saw_min, &
Zr%saw_max, &
Zr%saw, &
Zr%saw_u, &
Zr%asaw, &
Zr%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Nb") ::&
capi_40 = capi_saw_type(&
["n","o","b","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["N","b",c_null_char," "," "," "," "," "," "], &
Nb%z, &
Nb%saw_min, &
Nb%saw_max, &
Nb%saw, &
Nb%saw_u, &
Nb%asaw, &
Nb%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Mo") ::&
capi_41 = capi_saw_type(&
["m","o","l","y","b","d","e","n","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["M","o",c_null_char," "," "," "," "," "," "], &
Mo%z, &
Mo%saw_min, &
Mo%saw_max, &
Mo%saw, &
Mo%saw_u, &
Mo%asaw, &
Mo%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Tc") ::&
capi_42 = capi_saw_type(&
["t","e","c","h","n","e","t","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["T","c",c_null_char," "," "," "," "," "," "], &
Tc%z, &
Tc%saw_min, &
Tc%saw_max, &
Tc%saw, &
Tc%saw_u, &
Tc%asaw, &
Tc%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Ru") ::&
capi_43 = capi_saw_type(&
["r","u","t","h","e","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["R","u",c_null_char," "," "," "," "," "," "], &
Ru%z, &
Ru%saw_min, &
Ru%saw_max, &
Ru%saw, &
Ru%saw_u, &
Ru%asaw, &
Ru%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Rh") ::&
capi_44 = capi_saw_type(&
["r","h","o","d","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["R","h",c_null_char," "," "," "," "," "," "], &
Rh%z, &
Rh%saw_min, &
Rh%saw_max, &
Rh%saw, &
Rh%saw_u, &
Rh%asaw, &
Rh%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Pd") ::&
capi_45 = capi_saw_type(&
["p","a","l","l","a","d","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["P","d",c_null_char," "," "," "," "," "," "], &
Pd%z, &
Pd%saw_min, &
Pd%saw_max, &
Pd%saw, &
Pd%saw_u, &
Pd%asaw, &
Pd%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Ag") ::&
capi_46 = capi_saw_type(&
["s","i","l","v","e","r",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["A","g",c_null_char," "," "," "," "," "," "], &
Ag%z, &
Ag%saw_min, &
Ag%saw_max, &
Ag%saw, &
Ag%saw_u, &
Ag%asaw, &
Ag%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Cd") ::&
capi_47 = capi_saw_type(&
["c","a","d","m","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["C","d",c_null_char," "," "," "," "," "," "], &
Cd%z, &
Cd%saw_min, &
Cd%saw_max, &
Cd%saw, &
Cd%saw_u, &
Cd%asaw, &
Cd%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_In") ::&
capi_48 = capi_saw_type(&
["i","n","d","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["I","n",c_null_char," "," "," "," "," "," "], &
In%z, &
In%saw_min, &
In%saw_max, &
In%saw, &
In%saw_u, &
In%asaw, &
In%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Sn") ::&
capi_49 = capi_saw_type(&
["t","i","n",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["S","n",c_null_char," "," "," "," "," "," "], &
Sn%z, &
Sn%saw_min, &
Sn%saw_max, &
Sn%saw, &
Sn%saw_u, &
Sn%asaw, &
Sn%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Sb") ::&
capi_50 = capi_saw_type(&
["a","n","t","i","m","o","n","y",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["S","b",c_null_char," "," "," "," "," "," "], &
Sb%z, &
Sb%saw_min, &
Sb%saw_max, &
Sb%saw, &
Sb%saw_u, &
Sb%asaw, &
Sb%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Te") ::&
capi_51 = capi_saw_type(&
["t","e","l","l","u","r","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["T","e",c_null_char," "," "," "," "," "," "], &
Te%z, &
Te%saw_min, &
Te%saw_max, &
Te%saw, &
Te%saw_u, &
Te%asaw, &
Te%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_I") ::&
capi_52 = capi_saw_type(&
["i","o","d","i","n","e",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["I",c_null_char," "," "," "," "," "," "," "], &
I%z, &
I%saw_min, &
I%saw_max, &
I%saw, &
I%saw_u, &
I%asaw, &
I%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Xe") ::&
capi_53 = capi_saw_type(&
["x","e","n","o","n",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["X","e",c_null_char," "," "," "," "," "," "], &
Xe%z, &
Xe%saw_min, &
Xe%saw_max, &
Xe%saw, &
Xe%saw_u, &
Xe%asaw, &
Xe%saw_u, &
["g"," ","m",c_null_char," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Cs") ::&
capi_54 = capi_saw_type(&
["c","a","e","s","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["C","s",c_null_char," "," "," "," "," "," "], &
Cs%z, &
Cs%saw_min, &
Cs%saw_max, &
Cs%saw, &
Cs%saw_u, &
Cs%asaw, &
Cs%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Ba") ::&
capi_55 = capi_saw_type(&
["b","a","r","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["B","a",c_null_char," "," "," "," "," "," "], &
Ba%z, &
Ba%saw_min, &
Ba%saw_max, &
Ba%saw, &
Ba%saw_u, &
Ba%asaw, &
Ba%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_La") ::&
capi_56 = capi_saw_type(&
["l","a","n","t","h","a","n","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["L","a",c_null_char," "," "," "," "," "," "], &
La%z, &
La%saw_min, &
La%saw_max, &
La%saw, &
La%saw_u, &
La%asaw, &
La%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Ce") ::&
capi_57 = capi_saw_type(&
["c","e","r","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["C","e",c_null_char," "," "," "," "," "," "], &
Ce%z, &
Ce%saw_min, &
Ce%saw_max, &
Ce%saw, &
Ce%saw_u, &
Ce%asaw, &
Ce%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Pr") ::&
capi_58 = capi_saw_type(&
["p","r","a","s","e","o","d","y","m","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "], &
["P","r",c_null_char," "," "," "," "," "," "], &
Pr%z, &
Pr%saw_min, &
Pr%saw_max, &
Pr%saw, &
Pr%saw_u, &
Pr%asaw, &
Pr%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Nd") ::&
capi_59 = capi_saw_type(&
["n","e","o","d","y","m","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["N","d",c_null_char," "," "," "," "," "," "], &
Nd%z, &
Nd%saw_min, &
Nd%saw_max, &
Nd%saw, &
Nd%saw_u, &
Nd%asaw, &
Nd%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Pm") ::&
capi_60 = capi_saw_type(&
["p","r","o","m","e","t","h","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["P","m",c_null_char," "," "," "," "," "," "], &
Pm%z, &
Pm%saw_min, &
Pm%saw_max, &
Pm%saw, &
Pm%saw_u, &
Pm%asaw, &
Pm%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Sm") ::&
capi_61 = capi_saw_type(&
["s","a","m","a","r","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["S","m",c_null_char," "," "," "," "," "," "], &
Sm%z, &
Sm%saw_min, &
Sm%saw_max, &
Sm%saw, &
Sm%saw_u, &
Sm%asaw, &
Sm%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Eu") ::&
capi_62 = capi_saw_type(&
["e","u","r","o","p","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["E","u",c_null_char," "," "," "," "," "," "], &
Eu%z, &
Eu%saw_min, &
Eu%saw_max, &
Eu%saw, &
Eu%saw_u, &
Eu%asaw, &
Eu%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Gd") ::&
capi_63 = capi_saw_type(&
["g","a","d","o","l","i","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["G","d",c_null_char," "," "," "," "," "," "], &
Gd%z, &
Gd%saw_min, &
Gd%saw_max, &
Gd%saw, &
Gd%saw_u, &
Gd%asaw, &
Gd%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Tb") ::&
capi_64 = capi_saw_type(&
["t","e","r","b","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["T","b",c_null_char," "," "," "," "," "," "], &
Tb%z, &
Tb%saw_min, &
Tb%saw_max, &
Tb%saw, &
Tb%saw_u, &
Tb%asaw, &
Tb%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Dy") ::&
capi_65 = capi_saw_type(&
["d","y","s","p","r","o","s","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["D","y",c_null_char," "," "," "," "," "," "], &
Dy%z, &
Dy%saw_min, &
Dy%saw_max, &
Dy%saw, &
Dy%saw_u, &
Dy%asaw, &
Dy%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Ho") ::&
capi_66 = capi_saw_type(&
["h","o","l","m","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["H","o",c_null_char," "," "," "," "," "," "], &
Ho%z, &
Ho%saw_min, &
Ho%saw_max, &
Ho%saw, &
Ho%saw_u, &
Ho%asaw, &
Ho%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Er") ::&
capi_67 = capi_saw_type(&
["e","r","b","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["E","r",c_null_char," "," "," "," "," "," "], &
Er%z, &
Er%saw_min, &
Er%saw_max, &
Er%saw, &
Er%saw_u, &
Er%asaw, &
Er%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Tm") ::&
capi_68 = capi_saw_type(&
["t","h","u","l","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["T","m",c_null_char," "," "," "," "," "," "], &
Tm%z, &
Tm%saw_min, &
Tm%saw_max, &
Tm%saw, &
Tm%saw_u, &
Tm%asaw, &
Tm%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Yb") ::&
capi_69 = capi_saw_type(&
["y","t","t","e","r","b","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["Y","b",c_null_char," "," "," "," "," "," "], &
Yb%z, &
Yb%saw_min, &
Yb%saw_max, &
Yb%saw, &
Yb%saw_u, &
Yb%asaw, &
Yb%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Lu") ::&
capi_70 = capi_saw_type(&
["l","u","t","e","t","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["L","u",c_null_char," "," "," "," "," "," "], &
Lu%z, &
Lu%saw_min, &
Lu%saw_max, &
Lu%saw, &
Lu%saw_u, &
Lu%asaw, &
Lu%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Hf") ::&
capi_71 = capi_saw_type(&
["h","a","f","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["H","f",c_null_char," "," "," "," "," "," "], &
Hf%z, &
Hf%saw_min, &
Hf%saw_max, &
Hf%saw, &
Hf%saw_u, &
Hf%asaw, &
Hf%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Ta") ::&
capi_72 = capi_saw_type(&
["t","a","n","t","a","l","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["T","a",c_null_char," "," "," "," "," "," "], &
Ta%z, &
Ta%saw_min, &
Ta%saw_max, &
Ta%saw, &
Ta%saw_u, &
Ta%asaw, &
Ta%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_W") ::&
capi_73 = capi_saw_type(&
["t","u","n","g","s","t","e","n",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["W",c_null_char," "," "," "," "," "," "," "], &
W%z, &
W%saw_min, &
W%saw_max, &
W%saw, &
W%saw_u, &
W%asaw, &
W%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Re") ::&
capi_74 = capi_saw_type(&
["r","h","e","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["R","e",c_null_char," "," "," "," "," "," "], &
Re%z, &
Re%saw_min, &
Re%saw_max, &
Re%saw, &
Re%saw_u, &
Re%asaw, &
Re%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Os") ::&
capi_75 = capi_saw_type(&
["o","s","m","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["O","s",c_null_char," "," "," "," "," "," "], &
Os%z, &
Os%saw_min, &
Os%saw_max, &
Os%saw, &
Os%saw_u, &
Os%asaw, &
Os%saw_u, &
["g",c_null_char," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Ir") ::&
capi_76 = capi_saw_type(&
["i","r","i","d","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["I","r",c_null_char," "," "," "," "," "," "], &
Ir%z, &
Ir%saw_min, &
Ir%saw_max, &
Ir%saw, &
Ir%saw_u, &
Ir%asaw, &
Ir%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Pt") ::&
capi_77 = capi_saw_type(&
["p","l","a","t","i","n","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["P","t",c_null_char," "," "," "," "," "," "], &
Pt%z, &
Pt%saw_min, &
Pt%saw_max, &
Pt%saw, &
Pt%saw_u, &
Pt%asaw, &
Pt%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Au") ::&
capi_78 = capi_saw_type(&
["g","o","l","d",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["A","u",c_null_char," "," "," "," "," "," "], &
Au%z, &
Au%saw_min, &
Au%saw_max, &
Au%saw, &
Au%saw_u, &
Au%asaw, &
Au%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Hg") ::&
capi_79 = capi_saw_type(&
["m","e","r","c","u","r","y",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["H","g",c_null_char," "," "," "," "," "," "], &
Hg%z, &
Hg%saw_min, &
Hg%saw_max, &
Hg%saw, &
Hg%saw_u, &
Hg%asaw, &
Hg%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Tl") ::&
capi_80 = capi_saw_type(&
["t","h","a","l","l","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["T","l",c_null_char," "," "," "," "," "," "], &
Tl%z, &
Tl%saw_min, &
Tl%saw_max, &
Tl%saw, &
Tl%saw_u, &
Tl%asaw, &
Tl%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Pb") ::&
capi_81 = capi_saw_type(&
["l","e","a","d",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["P","b",c_null_char," "," "," "," "," "," "], &
Pb%z, &
Pb%saw_min, &
Pb%saw_max, &
Pb%saw, &
Pb%saw_u, &
Pb%asaw, &
Pb%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Bi") ::&
capi_82 = capi_saw_type(&
["b","i","s","m","u","t","h",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["B","i",c_null_char," "," "," "," "," "," "], &
Bi%z, &
Bi%saw_min, &
Bi%saw_max, &
Bi%saw, &
Bi%saw_u, &
Bi%asaw, &
Bi%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Po") ::&
capi_83 = capi_saw_type(&
["p","o","l","o","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["P","o",c_null_char," "," "," "," "," "," "], &
Po%z, &
Po%saw_min, &
Po%saw_max, &
Po%saw, &
Po%saw_u, &
Po%asaw, &
Po%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_At") ::&
capi_84 = capi_saw_type(&
["a","s","t","a","t","i","n","e",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["A","t",c_null_char," "," "," "," "," "," "], &
At%z, &
At%saw_min, &
At%saw_max, &
At%saw, &
At%saw_u, &
At%asaw, &
At%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Rn") ::&
capi_85 = capi_saw_type(&
["r","a","d","o","n",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["R","n",c_null_char," "," "," "," "," "," "], &
Rn%z, &
Rn%saw_min, &
Rn%saw_max, &
Rn%saw, &
Rn%saw_u, &
Rn%asaw, &
Rn%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Fr") ::&
capi_86 = capi_saw_type(&
["f","r","a","n","c","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["F","r",c_null_char," "," "," "," "," "," "], &
Fr%z, &
Fr%saw_min, &
Fr%saw_max, &
Fr%saw, &
Fr%saw_u, &
Fr%asaw, &
Fr%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Ra") ::&
capi_87 = capi_saw_type(&
["r","a","d","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["R","a",c_null_char," "," "," "," "," "," "], &
Ra%z, &
Ra%saw_min, &
Ra%saw_max, &
Ra%saw, &
Ra%saw_u, &
Ra%asaw, &
Ra%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Ac") ::&
capi_88 = capi_saw_type(&
["a","c","t","i","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["A","c",c_null_char," "," "," "," "," "," "], &
Ac%z, &
Ac%saw_min, &
Ac%saw_max, &
Ac%saw, &
Ac%saw_u, &
Ac%asaw, &
Ac%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Th") ::&
capi_89 = capi_saw_type(&
["t","h","o","r","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["T","h",c_null_char," "," "," "," "," "," "], &
Th%z, &
Th%saw_min, &
Th%saw_max, &
Th%saw, &
Th%saw_u, &
Th%asaw, &
Th%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Pa") ::&
capi_90 = capi_saw_type(&
["p","r","o","t","a","c","t","i","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "], &
["P","a",c_null_char," "," "," "," "," "," "], &
Pa%z, &
Pa%saw_min, &
Pa%saw_max, &
Pa%saw, &
Pa%saw_u, &
Pa%asaw, &
Pa%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_U") ::&
capi_91 = capi_saw_type(&
["u","r","a","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["U",c_null_char," "," "," "," "," "," "," "], &
U%z, &
U%saw_min, &
U%saw_max, &
U%saw, &
U%saw_u, &
U%asaw, &
U%saw_u, &
["g"," ","m",c_null_char," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Np") ::&
capi_92 = capi_saw_type(&
["n","e","p","t","u","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["N","p",c_null_char," "," "," "," "," "," "], &
Np%z, &
Np%saw_min, &
Np%saw_max, &
Np%saw, &
Np%saw_u, &
Np%asaw, &
Np%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Pu") ::&
capi_93 = capi_saw_type(&
["p","l","u","t","o","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["P","u",c_null_char," "," "," "," "," "," "], &
Pu%z, &
Pu%saw_min, &
Pu%saw_max, &
Pu%saw, &
Pu%saw_u, &
Pu%asaw, &
Pu%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Am") ::&
capi_94 = capi_saw_type(&
["a","m","e","r","i","c","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["A","m",c_null_char," "," "," "," "," "," "], &
Am%z, &
Am%saw_min, &
Am%saw_max, &
Am%saw, &
Am%saw_u, &
Am%asaw, &
Am%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Cm") ::&
capi_95 = capi_saw_type(&
["c","u","r","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["C","m",c_null_char," "," "," "," "," "," "], &
Cm%z, &
Cm%saw_min, &
Cm%saw_max, &
Cm%saw, &
Cm%saw_u, &
Cm%asaw, &
Cm%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Bk") ::&
capi_96 = capi_saw_type(&
["b","e","r","k","e","l","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["B","k",c_null_char," "," "," "," "," "," "], &
Bk%z, &
Bk%saw_min, &
Bk%saw_max, &
Bk%saw, &
Bk%saw_u, &
Bk%asaw, &
Bk%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Cf") ::&
capi_97 = capi_saw_type(&
["c","a","l","i","f","o","r","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["C","f",c_null_char," "," "," "," "," "," "], &
Cf%z, &
Cf%saw_min, &
Cf%saw_max, &
Cf%saw, &
Cf%saw_u, &
Cf%asaw, &
Cf%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Es") ::&
capi_98 = capi_saw_type(&
["e","i","n","s","t","e","i","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["E","s",c_null_char," "," "," "," "," "," "], &
Es%z, &
Es%saw_min, &
Es%saw_max, &
Es%saw, &
Es%saw_u, &
Es%asaw, &
Es%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Fm") ::&
capi_99 = capi_saw_type(&
["f","e","r","m","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["F","m",c_null_char," "," "," "," "," "," "], &
Fm%z, &
Fm%saw_min, &
Fm%saw_max, &
Fm%saw, &
Fm%saw_u, &
Fm%asaw, &
Fm%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Md") ::&
capi_100 = capi_saw_type(&
["m","e","n","d","e","l","e","v","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["M","d",c_null_char," "," "," "," "," "," "], &
Md%z, &
Md%saw_min, &
Md%saw_max, &
Md%saw, &
Md%saw_u, &
Md%asaw, &
Md%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_No") ::&
capi_101 = capi_saw_type(&
["n","o","b","e","l","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["N","o",c_null_char," "," "," "," "," "," "], &
No%z, &
No%saw_min, &
No%saw_max, &
No%saw, &
No%saw_u, &
No%asaw, &
No%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Lr") ::&
capi_102 = capi_saw_type(&
["l","a","w","r","e","n","c","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["L","r",c_null_char," "," "," "," "," "," "], &
Lr%z, &
Lr%saw_min, &
Lr%saw_max, &
Lr%saw, &
Lr%saw_u, &
Lr%asaw, &
Lr%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Rf") ::&
capi_103 = capi_saw_type(&
["r","u","t","h","e","r","f","o","r","d","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "], &
["R","f",c_null_char," "," "," "," "," "," "], &
Rf%z, &
Rf%saw_min, &
Rf%saw_max, &
Rf%saw, &
Rf%saw_u, &
Rf%asaw, &
Rf%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Db") ::&
capi_104 = capi_saw_type(&
["d","u","b","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["D","b",c_null_char," "," "," "," "," "," "], &
Db%z, &
Db%saw_min, &
Db%saw_max, &
Db%saw, &
Db%saw_u, &
Db%asaw, &
Db%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Sg") ::&
capi_105 = capi_saw_type(&
["s","e","a","b","o","r","g","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["S","g",c_null_char," "," "," "," "," "," "], &
Sg%z, &
Sg%saw_min, &
Sg%saw_max, &
Sg%saw, &
Sg%saw_u, &
Sg%asaw, &
Sg%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Bh") ::&
capi_106 = capi_saw_type(&
["b","o","h","r","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["B","h",c_null_char," "," "," "," "," "," "], &
Bh%z, &
Bh%saw_min, &
Bh%saw_max, &
Bh%saw, &
Bh%saw_u, &
Bh%asaw, &
Bh%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Hs") ::&
capi_107 = capi_saw_type(&
["h","a","s","s","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["H","s",c_null_char," "," "," "," "," "," "], &
Hs%z, &
Hs%saw_min, &
Hs%saw_max, &
Hs%saw, &
Hs%saw_u, &
Hs%asaw, &
Hs%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Mt") ::&
capi_108 = capi_saw_type(&
["m","e","i","t","n","e","r","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["M","t",c_null_char," "," "," "," "," "," "], &
Mt%z, &
Mt%saw_min, &
Mt%saw_max, &
Mt%saw, &
Mt%saw_u, &
Mt%asaw, &
Mt%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Ds") ::&
capi_109 = capi_saw_type(&
["d","a","r","m","s","t","a","d","t","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "], &
["D","s",c_null_char," "," "," "," "," "," "], &
Ds%z, &
Ds%saw_min, &
Ds%saw_max, &
Ds%saw, &
Ds%saw_u, &
Ds%asaw, &
Ds%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Rg") ::&
capi_110 = capi_saw_type(&
["r","o","e","n","t","g","e","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["R","g",c_null_char," "," "," "," "," "," "], &
Rg%z, &
Rg%saw_min, &
Rg%saw_max, &
Rg%saw, &
Rg%saw_u, &
Rg%asaw, &
Rg%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Cn") ::&
capi_111 = capi_saw_type(&
["c","o","p","e","r","n","i","c","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["C","n",c_null_char," "," "," "," "," "," "], &
Cn%z, &
Cn%saw_min, &
Cn%saw_max, &
Cn%saw, &
Cn%saw_u, &
Cn%asaw, &
Cn%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Nh") ::&
capi_112 = capi_saw_type(&
["n","i","h","o","n","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["N","h",c_null_char," "," "," "," "," "," "], &
Nh%z, &
Nh%saw_min, &
Nh%saw_max, &
Nh%saw, &
Nh%saw_u, &
Nh%asaw, &
Nh%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Fl") ::&
capi_113 = capi_saw_type(&
["f","l","e","r","o","v","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["F","l",c_null_char," "," "," "," "," "," "], &
Fl%z, &
Fl%saw_min, &
Fl%saw_max, &
Fl%saw, &
Fl%saw_u, &
Fl%asaw, &
Fl%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Mc") ::&
capi_114 = capi_saw_type(&
["m","o","s","c","o","v","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["M","c",c_null_char," "," "," "," "," "," "], &
Mc%z, &
Mc%saw_min, &
Mc%saw_max, &
Mc%saw, &
Mc%saw_u, &
Mc%asaw, &
Mc%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Lv") ::&
capi_115 = capi_saw_type(&
["l","i","v","e","r","m","o","r","i","u","m",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["L","v",c_null_char," "," "," "," "," "," "], &
Lv%z, &
Lv%saw_min, &
Lv%saw_max, &
Lv%saw, &
Lv%saw_u, &
Lv%asaw, &
Lv%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Ts") ::&
capi_116 = capi_saw_type(&
["t","e","n","n","e","s","i","n","e",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["T","s",c_null_char," "," "," "," "," "," "], &
Ts%z, &
Ts%saw_min, &
Ts%saw_max, &
Ts%saw, &
Ts%saw_u, &
Ts%asaw, &
Ts%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

type(capi_saw_type), protected, public, bind(C, name="ciaaw_saw_Og") ::&
capi_117 = capi_saw_type(&
["o","r","g","a","n","e","s","s","o","n",c_null_char," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["O","g",c_null_char," "," "," "," "," "," "], &
Og%z, &
Og%saw_min, &
Og%saw_max, &
Og%saw, &
Og%saw_u, &
Og%asaw, &
Og%saw_u, &
[c_null_char," "," "," "," "," "," "," "," "])

end module ciaaw__capi_saw_2021