module ciaaw__ice
    !! Ciaaw ice - Autogenerated
    !! See [specs](../page/specs/ciaaw_api.html)
    use ciaaw__common
    use ciaaw__types
    private

type(ice_type), parameter, public :: H_ice = &
ice_type(2,transpose(reshape([&
1.0_dp,0.99984426_dp,5e-8_dp,&
2.0_dp,0.00015574_dp,5e-8_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: He_ice = &
ice_type(2,transpose(reshape([&
3.0_dp,0.000001343_dp,13e-9_dp,&
4.0_dp,0.999998657_dp,13e-9_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Li_ice = &
ice_type(2,transpose(reshape([&
6.0_dp,0.07589_dp,24e-5_dp,&
7.0_dp,0.92411_dp,24e-5_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Be_ice = &
ice_type(1,transpose(reshape([&
9.0_dp,1.00000_dp,0.0000_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: B_ice = &
ice_type(2,transpose(reshape([&
10.0_dp,0.1982_dp,2e-4_dp,&
11.0_dp,0.8018_dp,2e-4_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: C_ice = &
ice_type(2,transpose(reshape([&
12.0_dp,0.988922_dp,28e-6_dp,&
13.0_dp,0.011078_dp,28e-6_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: N_ice = &
ice_type(2,transpose(reshape([&
14.0_dp,0.996337_dp,4e-6_dp,&
15.0_dp,0.003663_dp,4e-6_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: O_ice = &
ice_type(3,transpose(reshape([&
16.0_dp,0.9976206_dp,9e-7_dp,&
17.0_dp,0.0003790_dp,9e-7_dp,&
18.0_dp,0.0020004_dp,5e-7_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: F_ice = &
ice_type(1,transpose(reshape([&
19.0_dp,1.00000_dp,0.0000_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Ne_ice = &
ice_type(3,transpose(reshape([&
20.0_dp,0.904838_dp,90e-6_dp,&
21.0_dp,0.002696_dp,5e-6_dp,&
22.0_dp,0.092465_dp,90e-6_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Na_ice = &
ice_type(1,transpose(reshape([&
23.0_dp,1.00000_dp,0.0000_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Mg_ice = &
ice_type(3,transpose(reshape([&
24.0_dp,0.78951_dp,12e-5_dp,&
25.0_dp,0.10020_dp,8e-5_dp,&
26.0_dp,0.11029_dp,10e-5_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Al_ice = &
ice_type(1,transpose(reshape([&
27.0_dp,1.00000_dp,0.0000_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Si_ice = &
ice_type(3,transpose(reshape([&
28.0_dp,0.9222968_dp,44e-7_dp,&
29.0_dp,0.0468316_dp,32e-7_dp,&
30.0_dp,0.0308716_dp,32e-7_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: P_ice = &
ice_type(1,transpose(reshape([&
31.0_dp,1.00000_dp,0.0000_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: S_ice = &
ice_type(4,transpose(reshape([&
32.0_dp,0.9504074_dp,88e-7_dp,&
33.0_dp,0.0074869_dp,60e-7_dp,&
34.0_dp,0.0419599_dp,66e-7_dp,&
36.0_dp,0.0001458_dp,9e-7_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Cl_ice = &
ice_type(2,transpose(reshape([&
35.0_dp,0.757647_dp,38e-7_dp,&
37.0_dp,0.242353_dp,38e-7_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Ar_ice = &
ice_type(3,transpose(reshape([&
36.0_dp,0.0033361_dp,35e-7_dp,&
38.0_dp,0.0006289_dp,12e-7_dp,&
40.0_dp,0.9960350_dp,42e-7_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: K_ice = &
ice_type(3,transpose(reshape([&
39.0_dp,0.932581_dp,29e-6_dp,&
40.0_dp,0.0001167_dp,4e-7_dp,&
41.0_dp,0.067302_dp,29e-6_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Ca_ice = &
ice_type(6,transpose(reshape([&
40.0_dp,0.96941_dp,6e-5_dp,&
42.0_dp,0.00647_dp,3e-5_dp,&
43.0_dp,0.00135_dp,2e-5_dp,&
44.0_dp,0.02086_dp,4e-5_dp,&
46.0_dp,0.00004_dp,1e-5_dp,&
48.0_dp,0.00187_dp,1e-5_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Sc_ice = &
ice_type(1,transpose(reshape([&
45.0_dp,1.0000_dp,0.0000_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Ti_ice = &
ice_type(5,transpose(reshape([&
46.0_dp,0.08249_dp,21e-5_dp,&
47.0_dp,0.07437_dp,14e-5_dp,&
48.0_dp,0.73720_dp,20e-5_dp,&
49.0_dp,0.05409_dp,10e-5_dp,&
50.0_dp,0.05185_dp,13e-5_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: V_ice = &
ice_type(2,transpose(reshape([&
50.0_dp,0.002497_dp,6e-6_dp,&
51.0_dp,0.997503_dp,6e-6_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Cr_ice = &
ice_type(4,transpose(reshape([&
50.0_dp,0.043452_dp,85e-6_dp,&
52.0_dp,0.837895_dp,117e-6_dp,&
53.0_dp,0.095006_dp,110e-6_dp,&
54.0_dp,0.023647_dp,48e-6_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Mn_ice = &
ice_type(1,transpose(reshape([&
55.0_dp,1.0000_dp,0.0000_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Fe_ice = &
ice_type(4,transpose(reshape([&
54.0_dp,0.058450_dp,230e-6_dp,&
56.0_dp,0.917540_dp,240e-6_dp,&
57.0_dp,0.021191_dp,65e-6_dp,&
58.0_dp,0.002819_dp,27e-6_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Co_ice = &
ice_type(1,transpose(reshape([&
59.0_dp,1.0000_dp,0.0000_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Ni_ice = &
ice_type(5,transpose(reshape([&
58.0_dp,0.680769_dp,59e-6_dp,&
60.0_dp,0.262231_dp,51e-6_dp,&
61.0_dp,0.011399_dp,4e-6_dp,&
62.0_dp,0.036345_dp,11e-6_dp,&
64.0_dp,0.009256_dp,6e-6_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Cu_ice = &
ice_type(2,transpose(reshape([&
63.0_dp,0.69174_dp,20e-5_dp,&
65.0_dp,0.30826_dp,20e-5_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Zn_ice = &
ice_type(5,transpose(reshape([&
64.0_dp,0.491704_dp,83e-6_dp,&
66.0_dp,0.277306_dp,110e-6_dp,&
67.0_dp,0.040401_dp,18e-6_dp,&
68.0_dp,0.184483_dp,69e-6_dp,&
70.0_dp,0.006106_dp,11e-6_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Ga_ice = &
ice_type(2,transpose(reshape([&
69.0_dp,0.601079_dp,62e-6_dp,&
71.0_dp,0.398921_dp,62e-6_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Ge_ice = &
ice_type(5,transpose(reshape([&
70.0_dp,0.20526_dp,46e-5_dp,&
72.0_dp,0.27446_dp,15e-5_dp,&
73.0_dp,0.07760_dp,25e-5_dp,&
74.0_dp,0.36523_dp,63e-5_dp,&
76.0_dp,0.07745_dp,35e-5_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: As_ice = &
ice_type(1,transpose(reshape([&
75.0_dp,1.0000_dp,0.0000_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Se_ice = &
ice_type(6,transpose(reshape([&
74.0_dp,0.00863_dp,3e-5_dp,&
76.0_dp,0.09220_dp,6e-5_dp,&
77.0_dp,0.07594_dp,4e-5_dp,&
78.0_dp,0.23685_dp,14e-5_dp,&
80.0_dp,0.49813_dp,16e-5_dp,&
82.0_dp,0.08825_dp,8e-5_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Br_ice = &
ice_type(2,transpose(reshape([&
79.0_dp,0.50686_dp,25e-5_dp,&
81.0_dp,0.49314_dp,36e-5_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Kr_ice = &
ice_type(6,transpose(reshape([&
78.0_dp,0.0035518_dp,32e-7_dp,&
80.0_dp,0.0228560_dp,96e-7_dp,&
82.0_dp,0.115930_dp,62e-6_dp,&
83.0_dp,0.114996_dp,58e-6_dp,&
84.0_dp,0.569877_dp,58e-6_dp,&
86.0_dp,0.172790_dp,32e-6_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Rb_ice = &
ice_type(2,transpose(reshape([&
85.0_dp,0.721654_dp,132e-6_dp,&
87.0_dp,0.278346_dp,132e-6_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Sr_ice = &
ice_type(4,transpose(reshape([&
84.0_dp,0.005574_dp,16e-6_dp,&
86.0_dp,0.098566_dp,34e-6_dp,&
87.0_dp,0.070015_dp,26e-6_dp,&
88.0_dp,0.825845_dp,66e-6_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Y_ice = &
ice_type(1,transpose(reshape([&
89.0_dp,1.0000_dp,0.0000_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Zr_ice = &
ice_type(5,transpose(reshape([&
90.0_dp,0.51452_dp,9e-5_dp,&
91.0_dp,0.11223_dp,12e-5_dp,&
92.0_dp,0.17146_dp,7e-5_dp,&
94.0_dp,0.17380_dp,12e-5_dp,&
96.0_dp,0.02799_dp,5e-5_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Nb_ice = &
ice_type(1,transpose(reshape([&
93.0_dp,1.0000_dp,0.0000_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Mo_ice = &
ice_type(7,transpose(reshape([&
92.0_dp,0.14649_dp,17e-5_dp,&
94.0_dp,0.09187_dp,5e-5_dp,&
95.0_dp,0.15873_dp,5e-5_dp,&
96.0_dp,0.16673_dp,2e-5_dp,&
97.0_dp,0.09582_dp,3e-5_dp,&
98.0_dp,0.24292_dp,14e-5_dp,&
100.0_dp,0.09744_dp,10e-5_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Tc_ice = &
ice_type(0,transpose(reshape([&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

type(ice_type), parameter, public :: Rh_ice = &
ice_type(1,transpose(reshape([&
103.0_dp,1.0000_dp,0.0000_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp,&
-1.0_dp, -1.0_dp, -1.0_dp &
], shape=[3, 10])))

end module ciaaw__ice