module ciaaw__pte
    !! Ciaaw pte - Autogenerated
    !! See [specs](../page/specs/ciaaw_pte.html)
    use ciaaw__common
    use ciaaw__types
    use ciaaw__saw
    use ciaaw__ice
    use ciaaw__ice
    private

type(element_type), parameter, public :: pt(3) = [&
 element_type("hydrogen",          "H",       1,         H_saw,     H_ice     ),&
 element_type("helium",            "He",      2,         He_saw,    He_ice    ),&
 element_type("lithium",           "Li",      3,         Li_saw,    Li_ice    )&
]
end module ciaaw__pte
