module ciaaw__saw_capi
!! Standard Atomic Weights - autogenerated.
use iso_c_binding
use ciaaw__saw
implicit none

type, bind(C) :: ciaaw_saw_capi_elmt_t
character(kind=c_char) :: element(25)
character(kind=c_char) :: symbol(9)
integer(c_int) :: z
real(c_double) :: saw_min
real(c_double) :: saw_max
real(c_double) :: saw
real(c_double) :: saw_u
real(c_double) :: asaw
real(c_double) :: asaw_u
end type

integer(c_int), protected, bind(C, name="ciaaw_saw_capi_YEAR") :: ciaaw_saw_capi_YEAR = ciaaw_saw_YEAR

type(ciaaw_saw_capi_elmt_t), protected, bind(C, name="ciaaw_saw_capi_H") :: ciaaw_saw_capi_H = ciaaw_saw_capi_elmt_t(&
["h","y","d","r","o","g","e","n",c_null_char, " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["H",c_null_char, " "," "," "," "," "," "," "], &
ciaaw_saw_H%z, &
ciaaw_saw_H%saw_max, ciaaw_saw_H%saw_min, ciaaw_saw_H%saw, ciaaw_saw_H%saw_u, ciaaw_saw_H%asaw, ciaaw_saw_H%asaw_u)
type(ciaaw_saw_capi_elmt_t), protected, bind(C, name="ciaaw_saw_capi_He") :: ciaaw_saw_capi_He = ciaaw_saw_capi_elmt_t(&
["h","e","l","i","u","m",c_null_char, " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["H","e",c_null_char, " "," "," "," "," "," "], &
ciaaw_saw_He%z, &
ciaaw_saw_He%saw_max, ciaaw_saw_He%saw_min, ciaaw_saw_He%saw, ciaaw_saw_He%saw_u, ciaaw_saw_He%asaw, ciaaw_saw_He%asaw_u)
type(ciaaw_saw_capi_elmt_t), protected, bind(C, name="ciaaw_saw_capi_Li") :: ciaaw_saw_capi_Li = ciaaw_saw_capi_elmt_t(&
["l","i","t","h","i","u","m",c_null_char, " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["L","i",c_null_char, " "," "," "," "," "," "], &
ciaaw_saw_Li%z, &
ciaaw_saw_Li%saw_max, ciaaw_saw_Li%saw_min, ciaaw_saw_Li%saw, ciaaw_saw_Li%saw_u, ciaaw_saw_Li%asaw, ciaaw_saw_Li%asaw_u)
type(ciaaw_saw_capi_elmt_t), protected, bind(C, name="ciaaw_saw_capi_Be") :: ciaaw_saw_capi_Be = ciaaw_saw_capi_elmt_t(&
["b","e","r","y","l","l","i","u","m",c_null_char, " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["B","e",c_null_char, " "," "," "," "," "," "], &
ciaaw_saw_Be%z, &
ciaaw_saw_Be%saw_max, ciaaw_saw_Be%saw_min, ciaaw_saw_Be%saw, ciaaw_saw_Be%saw_u, ciaaw_saw_Be%asaw, ciaaw_saw_Be%asaw_u)
type(ciaaw_saw_capi_elmt_t), protected, bind(C, name="ciaaw_saw_capi_B") :: ciaaw_saw_capi_B = ciaaw_saw_capi_elmt_t(&
["b","o","r","o","n",c_null_char, " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["B",c_null_char, " "," "," "," "," "," "," "], &
ciaaw_saw_B%z, &
ciaaw_saw_B%saw_max, ciaaw_saw_B%saw_min, ciaaw_saw_B%saw, ciaaw_saw_B%saw_u, ciaaw_saw_B%asaw, ciaaw_saw_B%asaw_u)
type(ciaaw_saw_capi_elmt_t), protected, bind(C, name="ciaaw_saw_capi_C") :: ciaaw_saw_capi_C = ciaaw_saw_capi_elmt_t(&
["c","a","r","b","o","n",c_null_char, " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["C",c_null_char, " "," "," "," "," "," "," "], &
ciaaw_saw_C%z, &
ciaaw_saw_C%saw_max, ciaaw_saw_C%saw_min, ciaaw_saw_C%saw, ciaaw_saw_C%saw_u, ciaaw_saw_C%asaw, ciaaw_saw_C%asaw_u)
type(ciaaw_saw_capi_elmt_t), protected, bind(C, name="ciaaw_saw_capi_N") :: ciaaw_saw_capi_N = ciaaw_saw_capi_elmt_t(&
["n","i","t","r","o","g","e","n",c_null_char, " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["N",c_null_char, " "," "," "," "," "," "," "], &
ciaaw_saw_N%z, &
ciaaw_saw_N%saw_max, ciaaw_saw_N%saw_min, ciaaw_saw_N%saw, ciaaw_saw_N%saw_u, ciaaw_saw_N%asaw, ciaaw_saw_N%asaw_u)
type(ciaaw_saw_capi_elmt_t), protected, bind(C, name="ciaaw_saw_capi_O") :: ciaaw_saw_capi_O = ciaaw_saw_capi_elmt_t(&
["o","x","y","g","e","n",c_null_char, " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["O",c_null_char, " "," "," "," "," "," "," "], &
ciaaw_saw_O%z, &
ciaaw_saw_O%saw_max, ciaaw_saw_O%saw_min, ciaaw_saw_O%saw, ciaaw_saw_O%saw_u, ciaaw_saw_O%asaw, ciaaw_saw_O%asaw_u)
type(ciaaw_saw_capi_elmt_t), protected, bind(C, name="ciaaw_saw_capi_F") :: ciaaw_saw_capi_F = ciaaw_saw_capi_elmt_t(&
["f","l","u","o","r","i","n","e",c_null_char, " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["F",c_null_char, " "," "," "," "," "," "," "], &
ciaaw_saw_F%z, &
ciaaw_saw_F%saw_max, ciaaw_saw_F%saw_min, ciaaw_saw_F%saw, ciaaw_saw_F%saw_u, ciaaw_saw_F%asaw, ciaaw_saw_F%asaw_u)
type(ciaaw_saw_capi_elmt_t), protected, bind(C, name="ciaaw_saw_capi_Ne") :: ciaaw_saw_capi_Ne = ciaaw_saw_capi_elmt_t(&
["n","e","o","n",c_null_char, " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["N","e",c_null_char, " "," "," "," "," "," "], &
ciaaw_saw_Ne%z, &
ciaaw_saw_Ne%saw_max, ciaaw_saw_Ne%saw_min, ciaaw_saw_Ne%saw, ciaaw_saw_Ne%saw_u, ciaaw_saw_Ne%asaw, ciaaw_saw_Ne%asaw_u)
type(ciaaw_saw_capi_elmt_t), protected, bind(C, name="ciaaw_saw_capi_Na") :: ciaaw_saw_capi_Na = ciaaw_saw_capi_elmt_t(&
["s","o","d","i","u","m",c_null_char, " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["N","a",c_null_char, " "," "," "," "," "," "], &
ciaaw_saw_Na%z, &
ciaaw_saw_Na%saw_max, ciaaw_saw_Na%saw_min, ciaaw_saw_Na%saw, ciaaw_saw_Na%saw_u, ciaaw_saw_Na%asaw, ciaaw_saw_Na%asaw_u)
type(ciaaw_saw_capi_elmt_t), protected, bind(C, name="ciaaw_saw_capi_Mg") :: ciaaw_saw_capi_Mg = ciaaw_saw_capi_elmt_t(&
["m","a","g","n","e","s","i","u","m",c_null_char, " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["M","g",c_null_char, " "," "," "," "," "," "], &
ciaaw_saw_Mg%z, &
ciaaw_saw_Mg%saw_max, ciaaw_saw_Mg%saw_min, ciaaw_saw_Mg%saw, ciaaw_saw_Mg%saw_u, ciaaw_saw_Mg%asaw, ciaaw_saw_Mg%asaw_u)
type(ciaaw_saw_capi_elmt_t), protected, bind(C, name="ciaaw_saw_capi_Al") :: ciaaw_saw_capi_Al = ciaaw_saw_capi_elmt_t(&
["a","l","u","m","i","n","i","u","m",c_null_char, " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["A","l",c_null_char, " "," "," "," "," "," "], &
ciaaw_saw_Al%z, &
ciaaw_saw_Al%saw_max, ciaaw_saw_Al%saw_min, ciaaw_saw_Al%saw, ciaaw_saw_Al%saw_u, ciaaw_saw_Al%asaw, ciaaw_saw_Al%asaw_u)
type(ciaaw_saw_capi_elmt_t), protected, bind(C, name="ciaaw_saw_capi_Si") :: ciaaw_saw_capi_Si = ciaaw_saw_capi_elmt_t(&
["s","i","l","i","c","o","n",c_null_char, " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["S","i",c_null_char, " "," "," "," "," "," "], &
ciaaw_saw_Si%z, &
ciaaw_saw_Si%saw_max, ciaaw_saw_Si%saw_min, ciaaw_saw_Si%saw, ciaaw_saw_Si%saw_u, ciaaw_saw_Si%asaw, ciaaw_saw_Si%asaw_u)
type(ciaaw_saw_capi_elmt_t), protected, bind(C, name="ciaaw_saw_capi_P") :: ciaaw_saw_capi_P = ciaaw_saw_capi_elmt_t(&
["p","h","o","s","p","h","o","r","o","u","s",c_null_char, " "," "," "," "," "," "," "," "," "," "," "," "," "], &
["P",c_null_char, " "," "," "," "," "," "," "], &
ciaaw_saw_P%z, &
ciaaw_saw_P%saw_max, ciaaw_saw_P%saw_min, ciaaw_saw_P%saw, ciaaw_saw_P%saw_u, ciaaw_saw_P%asaw, ciaaw_saw_P%asaw_u)
type(ciaaw_saw_capi_elmt_t), protected, bind(C, name="ciaaw_saw_capi_S") :: ciaaw_saw_capi_S = ciaaw_saw_capi_elmt_t(&
["s","u","l","f","u","r",c_null_char, " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["S",c_null_char, " "," "," "," "," "," "," "], &
ciaaw_saw_S%z, &
ciaaw_saw_S%saw_max, ciaaw_saw_S%saw_min, ciaaw_saw_S%saw, ciaaw_saw_S%saw_u, ciaaw_saw_S%asaw, ciaaw_saw_S%asaw_u)
type(ciaaw_saw_capi_elmt_t), protected, bind(C, name="ciaaw_saw_capi_Cl") :: ciaaw_saw_capi_Cl = ciaaw_saw_capi_elmt_t(&
["c","h","l","o","r","i","n","e",c_null_char, " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["C","l",c_null_char, " "," "," "," "," "," "], &
ciaaw_saw_Cl%z, &
ciaaw_saw_Cl%saw_max, ciaaw_saw_Cl%saw_min, ciaaw_saw_Cl%saw, ciaaw_saw_Cl%saw_u, ciaaw_saw_Cl%asaw, ciaaw_saw_Cl%asaw_u)
type(ciaaw_saw_capi_elmt_t), protected, bind(C, name="ciaaw_saw_capi_Ar") :: ciaaw_saw_capi_Ar = ciaaw_saw_capi_elmt_t(&
["a","r","g","o","n",c_null_char, " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "], &
["A","r",c_null_char, " "," "," "," "," "," "], &
ciaaw_saw_Ar%z, &
ciaaw_saw_Ar%saw_max, ciaaw_saw_Ar%saw_min, ciaaw_saw_Ar%saw, ciaaw_saw_Ar%saw_u, ciaaw_saw_Ar%asaw, ciaaw_saw_Ar%asaw_u)

end module ciaaw__saw_capi
