module ciaaw__saw
!! Standard Atomic Weights - autogenerated.
use iso_fortran_env
implicit none

type :: ciaaw_saw_elmt_t
integer(int32) :: z
end type

integer(int32), parameter :: CIAAW_YEAR = 2021

end module ciaaw__saw
