module ciaaw__saw
!! Standard Atomic Weights - autogenerated.
use iso_fortran_env
use ieee_arithmetic
implicit none

type :: ciaaw_saw_elmt_t
character(len=32) :: element
character(len=2) :: symbol
integer(int32) :: z
real(real64) :: saw_min
real(real64) :: saw_max
real(real64) :: saw
real(real64) :: saw_u
real(real64) :: asaw
real(real64) :: asaw_u
end type

integer(int32), parameter :: ciaaw_saw_YEAR = 2021

type(ciaaw_saw_elmt_t), parameter :: ciaaw_saw_H =&
ciaaw_saw_elmt_t("hydrogen", "H", 1, 1.00784d0, 1.00811d0, 1.00798d0, 0.00008d0, 1.0080d0, 0.0002d0)

type(ciaaw_saw_elmt_t), parameter :: ciaaw_saw_He =&
ciaaw_saw_elmt_t("helium", "He", 2, -1, -1, 4.002602d0, 0.000002d0, 4.0026d0, 0.0001d0)

type(ciaaw_saw_elmt_t), parameter :: ciaaw_saw_Li =&
ciaaw_saw_elmt_t("lithium", "Li", 3, 6.938d0, 6.997d0, 6.97d0, 0.02d0, 6.94d0, 0.06d0)

type(ciaaw_saw_elmt_t), parameter :: ciaaw_saw_Be =&
ciaaw_saw_elmt_t("beryllium", "Be", 4, -1, -1, 9.0121831d0, 0.0000005, 9.0122, 0.00001d0)

type(ciaaw_saw_elmt_t), parameter :: ciaaw_saw_B =&
ciaaw_saw_elmt_t("boron", "B", 5, 10.806d0, 10.821d0, 10.813d0, 0.005d0, 10.81d0, 0.02d0)

type(ciaaw_saw_elmt_t), parameter :: ciaaw_saw_C =&
ciaaw_saw_elmt_t("carbon", "C", 6, 12.0096d0, 12.0116d0, 12.0106d0, 0.0006d0, 12.011d0, 0.002d0)

end module ciaaw__saw
