module ciaaw__version
!! Standard Atomic Weights - autogenerated.
use iso_fortran_env
use ieee_arithmetic
implicit none
private

character(len= 5), parameter, public :: ciaaw_version_version = "0.1.0"                                                         

end module ciaaw__version
