module ciaaw__version_capi
!! Version C API - autogenerated.
use iso_c_binding
use ciaaw__saw
implicit none
private

character(kind=c_char), protected, public, bind(C) :: ciaaw_version_capi_version( 6) = &
["0", ".", "1", ".", "0", c_null_char]

end module ciaaw__version_capi
