module ciaaw__saw_capi
!! Standard Atomic Weights - autogenerated.
use iso_c_binding
use ciaaw__saw
implicit none

type, bind(C) :: ciaaw_saw_capi_elmt_t
integer(c_int) :: z
end type

integer(c_int), protected, bind(C, name="CIAAW_CAPI_YEAR") :: CIAAW_CAPI_YEAR = CIAAW_YEAR

end module ciaaw__saw_capi
